Siril: update some deps
flathub/org.free_astro.siril pull request #25
Opened 2021-07-28 21:26 UTC by lock042

2021-07-28 21:36 UTC, hfiguiere requested changes

2021-07-28 21:36 UTC, hfiguiere commented on org.free_astro.siril.json
> +                    "sha256": "88735b69bb017ee92823b9e7ee14efeae2e57fb6c00503ed3aa2820e850a7b5e"
```suggestion
                    "url": "https://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/cfit-4.0.0.zip",
                    "sha256": "b70423f831dc28919c56ff37baebb50b1eaca665ca8ca34094cb58b60c482386"
```

this is where it is located.

2021-07-28 21:38 UTC, hfiguiere commented on org.free_astro.siril.json
> +                    "sha256": "88735b69bb017ee92823b9e7ee14efeae2e57fb6c00503ed3aa2820e850a7b5e"
nevermind

2021-07-28 21:42 UTC, hfiguiere approved these changes

2021-07-28 22:16 UTC, hfiguiere requested changes

2021-07-28 22:16 UTC, hfiguiere commented on org.free_astro.siril.json
> +            ",
```suggestion
            "name": "libraw",
```

This explain the build failure

2021-07-29 07:13 UTC, lock042 commented
@hfiguiere : I think an "autoreconf -fi" would be needed to libraw, before configure. How to add it?

2021-07-29 08:12 UTC, lock042 commented
> @hfiguiere : I think an "autoreconf -fi" would be needed to libraw, before configure. How to add it?
> 
> EDIT: I try something

OK. That looks good. I've tested it.
I merge.

2021-07-29 12:32 UTC, hfiguiere approved these changes

2021-08-01 00:42 UTC, merged

2021-08-01 10:06 UTC, lock042 commented
thanks @hfiguiere . Couldn't do it before :).